-- Data API grants must behave identically on legacy and newly-created
-- Supabase projects. Browser roles receive only explicit table grants, while
-- trusted Edge Functions retain access through service_role.
begin;

do $$
declare
  relation record;
begin
  for relation in
    select c.oid, n.nspname, c.relname
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname in ('public', 'security')
      and c.relkind in ('r', 'p')
  loop
    if not has_table_privilege('service_role', relation.oid, 'SELECT')
       or not has_table_privilege('service_role', relation.oid, 'INSERT')
       or not has_table_privilege('service_role', relation.oid, 'UPDATE')
       or not has_table_privilege('service_role', relation.oid, 'DELETE')
       or not has_table_privilege('service_role', relation.oid, 'TRUNCATE')
       or not has_table_privilege('service_role', relation.oid, 'REFERENCES')
       or not has_table_privilege('service_role', relation.oid, 'TRIGGER') then
      raise exception 'service_role lacks explicit table access to %.%', relation.nspname, relation.relname;
    end if;
  end loop;

  if exists (
    select 1
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relkind in ('r', 'p', 'v', 'm', 'f')
      and (
        has_table_privilege('anon', c.oid, 'SELECT')
        or has_table_privilege('anon', c.oid, 'INSERT')
        or has_table_privilege('anon', c.oid, 'UPDATE')
        or has_table_privilege('anon', c.oid, 'DELETE')
        or has_table_privilege('anon', c.oid, 'TRUNCATE')
        or has_table_privilege('anon', c.oid, 'REFERENCES')
        or has_table_privilege('anon', c.oid, 'TRIGGER')
      )
  ) then
    raise exception 'anon retained a direct public table privilege';
  end if;
end
$$;

-- Probe the effective defaults rather than only inspecting ACL text. A future
-- table must be server-only until its own migration grants authenticated access.
create table public.__data_api_grant_probe (
  id bigint generated by default as identity primary key,
  payload text
);
create function public.__data_api_function_probe()
returns integer language sql as $$ select 1 $$;

set local role supabase_admin;
create table public.__data_api_admin_grant_probe (
  id bigint generated by default as identity primary key,
  payload text
);
create function public.__data_api_admin_function_probe()
returns integer language sql as $$ select 1 $$;
reset role;

do $$
declare
  relation_name text;
begin
  for relation_name in
    select unnest(array['__data_api_grant_probe', '__data_api_admin_grant_probe'])
  loop
    if has_table_privilege('anon', format('public.%I', relation_name), 'SELECT')
       or has_table_privilege('anon', format('public.%I', relation_name), 'INSERT')
       or has_table_privilege('authenticated', format('public.%I', relation_name), 'SELECT')
       or has_table_privilege('authenticated', format('public.%I', relation_name), 'INSERT') then
      raise exception 'a browser role inherited privileges on %', relation_name;
    end if;
    if not has_table_privilege('service_role', format('public.%I', relation_name), 'SELECT')
       or not has_table_privilege('service_role', format('public.%I', relation_name), 'INSERT')
       or not has_table_privilege('service_role', format('public.%I', relation_name), 'UPDATE')
       or not has_table_privilege('service_role', format('public.%I', relation_name), 'DELETE') then
      raise exception 'service_role did not inherit CRUD privileges on %', relation_name;
    end if;
    if has_sequence_privilege('anon', format('public.%I', relation_name || '_id_seq'), 'USAGE')
       or has_sequence_privilege('authenticated', format('public.%I', relation_name || '_id_seq'), 'USAGE') then
      raise exception 'a browser role inherited sequence usage on %', relation_name;
    end if;
    if not has_sequence_privilege('service_role', format('public.%I', relation_name || '_id_seq'), 'USAGE')
       or not has_sequence_privilege('service_role', format('public.%I', relation_name || '_id_seq'), 'SELECT')
       or not has_sequence_privilege('service_role', format('public.%I', relation_name || '_id_seq'), 'UPDATE') then
      raise exception 'service_role did not inherit sequence privileges on %', relation_name;
    end if;
  end loop;

  for relation_name in
    select unnest(array['__data_api_function_probe()', '__data_api_admin_function_probe()'])
  loop
    if has_function_privilege('anon', format('public.%s', relation_name), 'EXECUTE')
       or has_function_privilege('authenticated', format('public.%s', relation_name), 'EXECUTE') then
      raise exception 'a browser role inherited function execution on %', relation_name;
    end if;
    if not has_function_privilege('service_role', format('public.%s', relation_name), 'EXECUTE') then
      raise exception 'service_role did not inherit function execution on %', relation_name;
    end if;
  end loop;
end
$$;

rollback;
