import { useEffect, useMemo, useState } from 'react'
import { S, fmt, relativeTime, PLATFORM_MAP, PLATFORM_COLORS } from './adminShared'
import type { Merchant, PerformanceData, SyncLog } from '../../lib/supabase'
import { supabase } from '../../lib/supabase'
import { localDateKey, performanceDateKey } from '../../lib/adminPerformance'
import { Activity, AlertTriangle, CalendarDays, CheckCircle2, ChevronDown, Layers3, PackageCheck, TrendingUp, Trophy, Users, Wallet } from 'lucide-react'
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, PieChart, Pie, Cell } from 'recharts'

type Preset = '7' | '30' | 'month' | 'custom'
type MetricPayload = {
  range:{start:string;end:string;previous_start:string;previous_end:string}
  totals:{gmv:number;orders:number;fees:number;active_merchants:number;rows:number;first_date:string|null;last_date:string|null;updated_at:string|null}
  previous:{gmv:number;orders:number;active_merchants:number}
  trend:Array<{date:string;gmv:number;orders:number}>
  platforms:Array<{platform:string;gmv:number;orders:number}>
  merchants:Array<{merchant_code:string;name:string;gmv:number;orders:number}>
}

function pct(current:number, previous:number) { return previous ? (current - previous) / previous * 100 : current ? null : 0 }
function dateBounds(preset:Preset, from:string, to:string) {
  const end = new Date(); let start = new Date(end)
  if (preset === 'custom') return [from,to] as const
  if (preset === 'month') start = new Date(end.getFullYear(), end.getMonth(), 1)
  else start.setDate(end.getDate() - Number(preset) + 1)
  return [localDateKey(start),localDateKey(end)] as const
}
function buildFallback(rows:PerformanceData[], start:string, end:string, platforms:string[], merchantCode:string):MetricPayload {
  const days = Math.max(1, Math.round((new Date(`${end}T00:00:00`).getTime() - new Date(`${start}T00:00:00`).getTime()) / 86400000) + 1)
  const previousEndDate = new Date(`${start}T00:00:00`); previousEndDate.setDate(previousEndDate.getDate() - 1)
  const previousStartDate = new Date(previousEndDate); previousStartDate.setDate(previousStartDate.getDate() - days + 1)
  const previousStart = localDateKey(previousStartDate); const previousEnd = localDateKey(previousEndDate)
  const inScope = (row:PerformanceData) => (!platforms.length || platforms.includes(row.platform)) && (!merchantCode || row.merchant_code === merchantCode)
  const current = rows.filter(row => inScope(row) && performanceDateKey(row) >= start && performanceDateKey(row) <= end)
  const previous = rows.filter(row => inScope(row) && performanceDateKey(row) >= previousStart && performanceDateKey(row) <= previousEnd)
  const total = (source:PerformanceData[]) => ({ gmv:source.reduce((s,r)=>s+Number(r.total_sales||0),0), orders:source.reduce((s,r)=>s+Number(r.order_count||0),0), active_merchants:new Set(source.map(r=>r.merchant_code)).size })
  const totals = total(current); const previousTotals = total(previous)
  const trendMap = new Map<string,{gmv:number;orders:number}>(); const cursor = new Date(`${start}T12:00:00`); const last = new Date(`${end}T12:00:00`)
  while(cursor<=last){trendMap.set(localDateKey(cursor),{gmv:0,orders:0});cursor.setDate(cursor.getDate()+1)}
  const platformMap = new Map<string,{gmv:number;orders:number}>(); const merchantMap = new Map<string,{gmv:number;orders:number}>()
  current.forEach(row=>{const d=trendMap.get(performanceDateKey(row));if(d){d.gmv+=Number(row.total_sales||0);d.orders+=Number(row.order_count||0)};const p=platformMap.get(row.platform)||{gmv:0,orders:0};p.gmv+=Number(row.total_sales||0);p.orders+=Number(row.order_count||0);platformMap.set(row.platform,p);const m=merchantMap.get(row.merchant_code)||{gmv:0,orders:0};m.gmv+=Number(row.total_sales||0);m.orders+=Number(row.order_count||0);merchantMap.set(row.merchant_code,m)})
  return {range:{start,end,previous_start:previousStart,previous_end:previousEnd},totals:{...totals,fees:current.reduce((s,r)=>s+Number(r.platform_fees||0),0),rows:current.length,first_date:current.length?current.map(performanceDateKey).sort()[0]:null,last_date:current.length?current.map(performanceDateKey).sort().slice(-1)[0]||null:null,updated_at:current.length?current.map(r=>r.created_at).sort().slice(-1)[0]||null:null},previous:previousTotals,trend:[...trendMap].map(([date,v])=>({date,...v})),platforms:[...platformMap].map(([platform,v])=>({platform,...v})).sort((a,b)=>b.gmv-a.gmv),merchants:[...merchantMap].map(([merchant_code,v])=>({merchant_code,name:merchant_code,...v})).sort((a,b)=>b.gmv-a.gmv).slice(0,10)}
}

export default function OverviewView({ merchantOnly, activeIntegrations, totalIntegrations, openTaskCount, syncLogs, perfData, onNavigate }: {merchantOnly:Merchant[];activeIntegrations:number;totalIntegrations:number;openTaskCount:number;syncLogs:SyncLog[];perfData:PerformanceData[];onNavigate:(target:string)=>void}) {
  const params = useMemo(()=>new URLSearchParams(window.location.search),[])
  const [preset,setPreset]=useState<Preset>(()=>['7','30','month','custom'].includes(params.get('period')||'')?params.get('period') as Preset:'30')
  const [platforms,setPlatforms]=useState<string[]>(()=>(params.get('platforms')||'').split(',').filter(Boolean))
  const [merchantCode,setMerchantCode]=useState(params.get('merchant')||'')
  const today=new Date(); const [from,setFrom]=useState(params.get('from')||localDateKey(new Date(today.getFullYear(),today.getMonth(),1))); const [to,setTo]=useState(params.get('to')||localDateKey(today))
  const [start,end]=dateBounds(preset,from,to)
  const [remote,setRemote]=useState<MetricPayload|null>(null); const [metricsError,setMetricsError]=useState(''); const [metricsLoading,setMetricsLoading]=useState(false)
  const availablePlatforms=useMemo(()=>[...new Set(['amazon','noon','trendyol','salla','zid','shopify',...perfData.map(row=>row.platform)])].filter(platform=>platform!=='other').sort(),[perfData])
  const fallback=useMemo(()=>buildFallback(perfData,start,end,platforms,merchantCode),[perfData,start,end,platforms,merchantCode])
  const metrics=remote||fallback

  useEffect(()=>{const next=new URLSearchParams(window.location.search);next.set('period',preset);if(platforms.length)next.set('platforms',platforms.join(','));else next.delete('platforms');if(merchantCode)next.set('merchant',merchantCode);else next.delete('merchant');if(preset==='custom'){next.set('from',from);next.set('to',to)}else{next.delete('from');next.delete('to')}window.history.replaceState(null,'',`${window.location.pathname}?${next.toString()}`)},[preset,platforms,merchantCode,from,to])
  useEffect(()=>{let cancelled=false;setMetricsLoading(true);setMetricsError('');supabase.rpc('admin_overview_metrics',{p_start_date:start,p_end_date:end,p_platforms:platforms.length?platforms:null,p_merchant_code:merchantCode||null}).then(({data,error})=>{if(cancelled)return;if(error){setRemote(null);setMetricsError('تعذر تشغيل التجميع السريع؛ تم عرض البيانات المحلية المتاحة.')}else setRemote(data as MetricPayload);setMetricsLoading(false)});return()=>{cancelled=true}},[start,end,platforms,merchantCode])

  const currentGMV=Number(metrics.totals.gmv||0), currentOrders=Number(metrics.totals.orders||0), active=Number(metrics.totals.active_merchants||0)
  const avg=active?currentGMV/active:0, gmvDelta=pct(currentGMV,Number(metrics.previous.gmv||0)), orderDelta=pct(currentOrders,Number(metrics.previous.orders||0))
  const failedImports=syncLogs.filter(log=>log.status==='error'||log.status==='stalled').length, inactiveIntegrations=Math.max(0,totalIntegrations-activeIntegrations)
  const oldestDate=metrics.totals.first_date, latestDate=metrics.totals.last_date
  const scopeLabel=`${new Intl.DateTimeFormat('ar-SA-u-ca-gregory-nu-latn',{day:'numeric',month:'short'}).format(new Date(`${start}T00:00:00`))} – ${new Intl.DateTimeFormat('ar-SA-u-ca-gregory-nu-latn',{day:'numeric',month:'short',year:'numeric'}).format(new Date(`${end}T00:00:00`))}`
  const actions=[{label:'استيرادات متعثرة',value:failedImports,detail:'ضمن آخر 20 عملية',attention:failedImports>0,target:'uploads'},{label:'مهام مفتوحة',value:openTaskCount,detail:'تحتاج متابعة الفريق',attention:openTaskCount>0,target:'tasks'},{label:'اتصالات غير نشطة',value:inactiveIntegrations,detail:`${activeIntegrations} اتصال نشط`,attention:inactiveIntegrations>0,target:'connections'}]
  function togglePlatform(platform:string){setPlatforms(current=>current.includes(platform)?current.filter(value=>value!==platform):[...current,platform].sort())}

  return <div style={{display:'flex',flexDirection:'column',gap:20}}>
    <section className="admin-overview-filters" aria-label="فلاتر جميع بيانات نظرة عامة" style={{...S.chartCard,padding:14,display:'flex',gap:10,alignItems:'center',flexWrap:'wrap'}}>
      <div style={{display:'flex',alignItems:'center',gap:7,color:'var(--accent)',fontWeight:800,fontSize:12}}><CalendarDays size={16}/><select aria-label="الفترة الزمنية لجميع بيانات نظرة عامة" value={preset} onChange={event=>setPreset(event.target.value as Preset)} style={S.filterSelect}><option value="7">آخر 7 أيام</option><option value="30">آخر 30 يومًا</option><option value="month">هذا الشهر</option><option value="custom">فترة مخصصة</option></select></div>
      <details style={{position:'relative'}}><summary style={{...S.filterSelect,listStyle:'none',display:'flex',alignItems:'center',gap:7,cursor:'pointer',minHeight:44}}><Layers3 size={15}/>{platforms.length?`${platforms.length} منصات`:'كل المنصات'}<ChevronDown size={14}/></summary><div style={{position:'absolute',zIndex:20,top:'calc(100% + 6px)',right:0,minWidth:210,padding:8,border:'1px solid var(--border)',borderRadius:10,background:'var(--surface)',boxShadow:'0 16px 40px rgba(19,43,58,.14)'}}><label style={{display:'flex',gap:8,padding:8}}><input type="checkbox" checked={!platforms.length} onChange={()=>setPlatforms([])}/>كل المنصات</label>{availablePlatforms.map(platform=><label key={platform} style={{display:'flex',gap:8,padding:8}}><input type="checkbox" checked={platforms.includes(platform)} onChange={()=>togglePlatform(platform)}/>{PLATFORM_MAP[platform]||platform}</label>)}</div></details>
      <select aria-label="التاجر لجميع بيانات نظرة عامة" value={merchantCode} onChange={event=>setMerchantCode(event.target.value)} style={{...S.filterSelect,minHeight:44}}><option value="">كل التجار</option>{merchantOnly.map(merchant=><option key={merchant.id} value={merchant.merchant_code}>{merchant.name}</option>)}</select>
      {preset==='custom'&&<><label style={{fontSize:11,color:'var(--text3)'}}>من <input type="date" value={from} max={to} onChange={event=>setFrom(event.target.value)} style={S.filterSelect}/></label><label style={{fontSize:11,color:'var(--text3)'}}>إلى <input type="date" value={to} min={from} onChange={event=>setTo(event.target.value)} style={S.filterSelect}/></label></>}
      <span style={{marginRight:'auto',fontSize:11,color:'var(--text3)'}}>{metricsLoading?'جارٍ التحديث…':`${scopeLabel}${metrics.totals.updated_at?` · آخر تجميع ${relativeTime(metrics.totals.updated_at)}`:''}`}</span>
    </section>
    {metricsError&&<div role="status" style={{padding:'9px 12px',borderRadius:8,background:'var(--warning-bg)',color:'var(--warning-text)',fontSize:11}}>{metricsError}</div>}
    <div data-kpi-grid style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:14}}>
      <Kpi label="التجار النشطون" value={active.toLocaleString('ar-SA-u-nu-latn')} sub={`ضمن النطاق المحدد · من ${merchantOnly.length}`} Icon={Users} color="#0f958c" onClick={()=>onNavigate('merchants')}/>
      <Kpi label="GMV في النطاق" value={fmt(currentGMV)} sub={`الفترة السابقة: ${fmt(Number(metrics.previous.gmv||0))}`} delta={gmvDelta} Icon={Wallet} color="#00a884" onClick={()=>onNavigate('performance')}/>
      <Kpi label="الوحدات / الطلبات" value={currentOrders.toLocaleString('ar-SA-u-nu-latn')} sub={`الفترة السابقة: ${Number(metrics.previous.orders||0).toLocaleString('ar-SA-u-nu-latn')}`} delta={orderDelta} Icon={PackageCheck} color="#d18400" onClick={()=>onNavigate('performance')}/>
      <Kpi label="متوسط GMV / تاجر نشط" value={fmt(avg)} sub="البسط والمقام من النطاق نفسه" Icon={TrendingUp} color="#2788a8" onClick={()=>onNavigate('performance')}/>
    </div>
    <section style={{...S.chartCard,padding:16}}><div style={{display:'flex',alignItems:'center',gap:8,marginBottom:12}}><Activity size={17} color="var(--accent)"/><div><div style={S.chartTitle}>مركز الإجراءات — الآن</div><div style={S.chartSub}>مؤشرات تشغيلية حالية لا تتأثر بالفترة التاريخية</div></div></div><div className="grid-mobile-2" style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:10}}>{actions.map(action=><button type="button" key={action.label} onClick={()=>onNavigate(action.target)} style={{border:`1px solid ${action.attention?'rgba(232,64,64,.25)':'var(--border)'}`,borderRadius:10,padding:12,minHeight:96,background:action.attention?'var(--danger-bg)':'var(--surface2)',textAlign:'right',fontFamily:'inherit',cursor:'pointer'}}><div style={{display:'flex',justifyContent:'space-between'}}><span style={{fontSize:11,fontWeight:700}}>{action.label}</span>{action.attention?<AlertTriangle size={14} color="var(--red)"/>:<CheckCircle2 size={14} color="var(--accent2)"/>}</div><strong style={{display:'block',fontSize:22,color:action.attention?'var(--red)':'var(--accent2)',marginTop:6}}>{action.value.toLocaleString('ar-SA-u-nu-latn')}</strong><small style={{color:'var(--text3)'}}>{action.detail}</small></button>)}</div></section>
    <div className="grid-mobile-1" style={{display:'grid',gridTemplateColumns:'2fr 1fr',gap:14}}>
      <section style={S.chartCard}><div style={{display:'flex',justifyContent:'space-between',gap:10,marginBottom:14,flexWrap:'wrap'}}><div><div style={S.chartTitle}>اتجاه الإيرادات</div><div style={S.chartSub}>{scopeLabel} · جميع الفلاتر أعلاه مطبقة</div></div><span style={{fontSize:10,color:'var(--text3)'}}>تغطية البيانات: {oldestDate||'—'} إلى {latestDate||'—'}</span></div>{metrics.trend.length?<><div aria-label={`إجمالي GMV ${fmt(currentGMV)}`}><ResponsiveContainer width="100%" height={230}><AreaChart data={metrics.trend.map(row=>({...row,label:new Date(`${row.date}T00:00:00`).toLocaleDateString('ar-SA-u-ca-gregory-nu-latn',{day:'numeric',month:'short'})}))}><defs><linearGradient id="adminGmvGrad" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="var(--accent)" stopOpacity={.35}/><stop offset="95%" stopColor="var(--accent)" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="var(--border)"/><XAxis dataKey="label" tick={{fill:'var(--text3)',fontSize:10}} axisLine={false}/><YAxis tick={{fill:'var(--text3)',fontSize:10}} axisLine={false} tickFormatter={value=>value>=1000?`${(value/1000).toFixed(0)}k`:value}/><Tooltip formatter={(value:number)=>[fmt(value),'GMV']}/><Area type="monotone" dataKey="gmv" stroke="var(--accent)" strokeWidth={2.5} fill="url(#adminGmvGrad)" dot={false}/></AreaChart></ResponsiveContainer></div><details className="chart-data"><summary>عرض القيم كجدول</summary><div><table><thead><tr><th>التاريخ</th><th>GMV</th><th>الطلبات</th></tr></thead><tbody>{metrics.trend.map(row=><tr key={row.date}><td>{row.date}</td><td>{fmt(Number(row.gmv))}</td><td>{Number(row.orders).toLocaleString('ar-SA-u-nu-latn')}</td></tr>)}</tbody></table></div></details></>:<div style={S.emptyChart}>لا توجد بيانات في النطاق</div>}</section>
      <section style={S.chartCard}><div style={S.chartTitle}>توزيع المنصات</div><div style={S.chartSub}>من GMV النطاق المحدد</div>{metrics.platforms.length>1?<ResponsiveContainer width="100%" height={170}><PieChart><Pie data={metrics.platforms} dataKey="gmv" nameKey="platform" innerRadius={42} outerRadius={67} paddingAngle={4}>{metrics.platforms.map(row=><Cell key={row.platform} fill={PLATFORM_COLORS[row.platform]||'#64748b'}/>)}</Pie><Tooltip formatter={(value:number,_name,props)=>[fmt(value),PLATFORM_MAP[props.payload.platform]||props.payload.platform]}/></PieChart></ResponsiveContainer>:metrics.platforms.length===1?<div style={{padding:'34px 0',textAlign:'center'}}><strong style={{display:'block',fontSize:18,color:PLATFORM_COLORS[metrics.platforms[0].platform]||'var(--accent)'}}>{PLATFORM_MAP[metrics.platforms[0].platform]||metrics.platforms[0].platform}</strong><span style={{display:'block',marginTop:8}}>{fmt(Number(metrics.platforms[0].gmv))}</span></div>:<div style={S.emptyChart}>لا توجد بيانات</div>}<div style={{display:'grid',gap:8}}>{metrics.platforms.map(row=>{const share=currentGMV?Number(row.gmv)/currentGMV*100:0;return <div key={row.platform} style={{display:'flex',justifyContent:'space-between',fontSize:11}}><span><i style={{display:'inline-block',width:8,height:8,borderRadius:'50%',background:PLATFORM_COLORS[row.platform]||'#64748b',marginLeft:6}}/>{PLATFORM_MAP[row.platform]||row.platform}</span><b>{share.toFixed(1)}%</b></div>})}</div></section>
    </div>
    <div className="grid-mobile-1" style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:14}}><section style={S.chartCard}><div style={{...S.chartTitle,display:'flex',gap:7}}><Trophy size={16} color="var(--warning-text)"/>أفضل التجار ضمن النطاق</div><div style={{display:'grid',gap:11,marginTop:15}}>{metrics.merchants.length?metrics.merchants.slice(0,5).map((row,index)=><div key={row.merchant_code} style={{display:'grid',gridTemplateColumns:'24px 1fr auto',gap:8,alignItems:'center'}}><b style={{color:'var(--text3)'}}>{index+1}</b><span style={{fontSize:12}}>{merchantOnly.find(m=>m.merchant_code===row.merchant_code)?.name||row.name}</span><strong style={{fontSize:12,color:'var(--accent)'}}>{fmt(Number(row.gmv))}</strong></div>):<div style={S.emptyChart}>لا توجد بيانات</div>}</div></section><section style={S.chartCard}><div style={S.chartTitle}>آخر النشاطات — الآن</div><div style={{display:'grid',gap:10,marginTop:15}}>{syncLogs.length?syncLogs.slice(0,6).map(log=><div key={log.id} style={{display:'flex',justifyContent:'space-between',gap:10,paddingBottom:9,borderBottom:'1px solid var(--border)',fontSize:11}}><span><b>{log.merchant_code}</b> · {PLATFORM_MAP[log.platform]||log.platform}</span><span style={{color:log.status==='success'?'var(--success-text)':'var(--danger-text)'}}>{relativeTime(log.started_at)}</span></div>):<div style={S.emptyChart}>لا توجد نشاطات</div>}</div></section></div>
  </div>
}

function Kpi({label,value,sub,delta,Icon,color,onClick}:{label:string;value:string;sub:string;delta?:number|null;Icon:any;color:string;onClick:()=>void}){return <button type="button" onClick={onClick} style={{...S.kpiCard,padding:18,textAlign:'right',fontFamily:'inherit',cursor:'pointer',width:'100%',minHeight:132}}><div style={{...S.kpiBar,background:color}}/><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><span style={{fontSize:11,color:'var(--text3)',fontWeight:700}}>{label}</span><Icon size={16} color={color}/></div><strong style={{display:'block',fontSize:22,color,marginTop:10,direction:'ltr',textAlign:'right'}}>{value}</strong><div style={{display:'flex',gap:7,alignItems:'center',marginTop:7}}><small style={{color:'var(--text3)',flex:1}}>{sub}</small>{delta!==undefined&&<span style={{fontSize:10,fontWeight:800,color:delta===null?'var(--text2)':delta>=0?'var(--success-text)':'var(--danger-text)'}}>{delta===null?'جديد':`${delta>=0?'▲':'▼'} ${Math.abs(delta).toFixed(1)}%`}</span>}</div></button>}
